[[shortcut]]
command = "Std_DlgCustomize"
shortcut = "Q, Q"

[[shortcut]]
command = "Std_Delete"
shortcut = "Q, D"

[[shortcut]]
command = "Sketcher_LeaveSketch"
shortcut = "Q, Esc"

[[shortcut]]
command = "Sketcher_ViewSection"
shortcut = "Q, S"

[[shortcut]]
command = "Sketcher_CreateLine"
shortcut = "G, F"

[[shortcut]]
command = "Std_ViewHome"
shortcut = "V, H"
